// Path Url

// Production
export const apiUrl = "http://191.101.38.12:4000/api";
export const imageUrl = "http://191.101.38.12:4000";

// Developement
// export const apiUrl = "http://127.0.0.1:4000/api";
// export const imageUrl = "http://127.0.0.1:4000";

export const server = {
  REGISTER_URL: "/authen/user",
  GET_USER_URL: "/authen/user",
  GET_USERS_URL: "/authen/users",
  LOGIN_URL: "/authen/login",
  PRODUCTS_URL: "/stock/product",
  PRODUCTS_SLICE_URL: "/stock/getProducts",
  SALEORDER_URL: "/saleorder",
  SALEORDERLIST_URL: "/saleorderlist",
  GET_USER_SALEORDERLIST_URL: "/saleorderlist/getSaleOrderList",
  GET_ADMIN_SALEORDERLIST_URL: "/saleorderlist/getSaleOrderLists",
  GET_DETAIL_SALEORDER_URL: "/saleorder/saleorder-detail",
};

// Config Menu Serach Page
export const limit = 5;
export const page = 1;

export const NOT_CONNECT_NETWORK = "ERROR NETWORK";
export const NETWORK_CONNECTION_MESSAGE = "OK";

// Constants SaleOrder Page
export const HTTP_CREATE_SALEORDER_FETCHING = "HTTP_CREATE_SALEORDER_FETCHING";
export const HTTP_CREATE_SALEORDER_SUCCESS = "HTTP_CREATE_SALEORDER_SUCCESS";
export const HTTP_CREATE_SALEORDER_FAILED = "HTTP_CREATE_SALEORDER_FAILED";

// Constants User Page
export const HTTP_GET_USERS_FETCHING = "HTTP_GET_USERS_FETCHING";
export const HTTP_GET_USERS_SUCCESS = "HTTP_GET_USERS_SUCCESS";
export const HTTP_GET_USERS_FAILED = "HTTP_GET_USERS_FAILED";

// Constants Edit Page
export const HTTP_EDIT_USER_FETCHING = "HTTP_EDIT_USER_FETCHING";
export const HTTP_EDIT_USER_SUCCESS = "HTTP_EDIT_USER_SUCCESS";
export const HTTP_EDIT_USER_FAILED = "HTTP_EDIT_USER_FAILED";

// Constants User Page
export const HTTP_GET_USER_FETCHING = "HTTP_GET_USER_FETCHING";
export const HTTP_GET_USER_SUCCESS = "HTTP_GET_USER_SUCCESS";
export const HTTP_GET_USER_FAILED = "HTTP_GET_USER_FAILED";

// Constants SaleOrder List Page
export const HTTP_CREATE_SALEORDERLIST_FETCHING = "HTTP_CREATE_SALEORDERLIST_FETCHING";
export const HTTP_CREATE_SALEORDERLIST_SUCCESS = "HTTP_CREATE_SALEORDERLIST_SUCCESS";
export const HTTP_CREATE_SALEORDERLIST_FAILED = "HTTP_CREATE_SALEORDERLIST_FAILED";

export const HTTP_GET_SALEORDERLIST_FETCHING = "HTTP_GET_SALEORDERLIST_FETCHING";
export const HTTP_GET_SALEORDERLIST_SUCCESS = "HTTP_GET_SALEORDERLIST_SUCCESS";
export const HTTP_GET_SALEORDERLIST_FAILED = "HTTP_GET_SALEORDERLIST_FAILED";


// Constants Update SaleOrder to Stock Page
export const HTTP_UPDATE_SALEORDER_FETCHING = "HTTP_UPDATE_SALEORDER_FETCHING";
export const HTTP_UPDATE_SALEORDER_SUCCESS = "HTTP_UPDATE_SALEORDER_SUCCESS";
export const HTTP_UPDATE_SALEORDER_FAILED = "HTTP_UPDATE_SALEORDER_FAILED";

// Constants Get SaleOrder Detail to Saleorder Detail Page
export const HTTP_DETAIL_SALEORDER_FETCHING = "HTTP_DETAIL_SALEORDER_FETCHING";
export const HTTP_DETAIL_SALEORDER_SUCCESS = "HTTP_DETAIL_SALEORDER_SUCCESS";
export const HTTP_DETAIL_SALEORDER_FAILED = "HTTP_DETAIL_SALEORDER_FAILED";

// Constatns Register Page
export const HTTP_REGISTER_FETCHING = "HTTP_REGISTER_FETCHING";
export const HTTP_REGISTER_SUCCESS = "HTTP_REGISTER_SUCCESS";
export const HTTP_REGISTER_FAILED = "HTTP_REGISTER_FAILED";
export const HTTP_REGISTER_DUPLICATE = "HTTP_REGISTER_DUPLICATE";
export const HTTP_REGISTER_RESET = "HTTP_REGISTER_RESET";

// Constatns login Page
export const HTTP_LOGIN_FETCHING = "HTTP_LOGIN_FETCHING";
export const HTTP_LOGIN_SUCCESS = "HTTP_LOGIN_SUCCESS";
export const HTTP_LOGIN_FAILED = "HTTP_LOGIN_FAILED";

// Constatns Stock Page
export const HTTP_STOCK_FETCHING = "HTTP_STOCK_FETCHING";
export const HTTP_STOCK_SUCCESS = "HTTP_STOCK_SUCCESS";
export const HTTP_STOCK_FAILED = "HTTP_STOCK_FAILED";

// Constatns StockCreate Page
export const HTTP_ADD_STOCK_FETCHING = "HTTP_ADD_STOCK_FETCHING";
export const HTTP_ADD_STOCK_SUCCESS = "HTTP_ADD_STOCK_SUCCESS";
export const HTTP_ADD_STOCK_FAILED = "HTTP_ADD_STOCK_FAILED";
export const HTTP_ADD_STOCK_DUPLICATE = "HTTP_ADD_STOCK_DUPLICATE";

// Constatns StockEdit Page
export const HTTP_DEIT_STOCK_FETCHING = "HTTP_DEIT_STOCK_FETCHING";
export const HTTP_DEIT_STOCK_SUCCESS = "HTTP_DEIT_STOCK_SUCCESS";
export const HTTP_DEIT_STOCK_FAILED = "HTTP_DEIT_STOCK_FAILED";




// APP Page
export const APP_INIT = "APP_INIT";

